"""add uf_emit and uf_dest to documentos_fiscais

Revision ID: 0d4ae9c423e0
Revises: 
Create Date: 2026-03-23 21:15:55.053294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4ae9c423e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos_fiscais', sa.Column('uf_emit', sa.String(length=2), nullable=True))
    op.add_column('documentos_fiscais', sa.Column('uf_dest', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos_fiscais', 'uf_dest')
    op.drop_column('documentos_fiscais', 'uf_emit')
    # ### end Alembic commands ###
