"""add_cpf_to_usuarios

Revision ID: 9196733fb8a5
Revises: 617775975286
Create Date: 2026-04-22 14:14:29.472550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9196733fb8a5'
down_revision: Union[str, Sequence[str], None] = '617775975286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('cpf', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_column('usuarios', 'cpf')
    # ### end Alembic commands ###
