"""add_insight_superseded

Revision ID: b2422ebc2669
Revises: 5046f56e0cfc
Create Date: 2026-04-27 16:31:41.830818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2422ebc2669'
down_revision: Union[str, Sequence[str], None] = '5046f56e0cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "insights",
        sa.Column("superseded", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("insights", "superseded")
    # ### end Alembic commands ###
