"""ADR-020 atomic policy and normative activation foundation.

Revision ID: 0024_adr020_activation
Revises: 0023_adr020_coverage
PostgreSQL-only foundation without runtime operation.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0024_adr020_activation"
down_revision: str = "0023_adr020_coverage"
branch_labels = None
depends_on = None

TABLES = ("policy_activation_executions", "policy_activations", "activation_decisions", "activation_executions", "normative_activations", "activation_generations", "outbox_event_records")

def _require_postgresql():
    if op.get_bind().dialect.name != "postgresql":
        raise RuntimeError("Migration 0024_adr020_activation is PostgreSQL-only")

def J(name, nullable=False): return sa.Column(name, postgresql.JSONB(astext_type=sa.Text()), nullable=nullable)
def S(name, nullable=False): return sa.Column(name, sa.String(64), nullable=nullable)
def H(name, nullable=False): return S(name, nullable)
def _append_only(table):
    op.execute(f"CREATE TRIGGER trg_{table}_append_only_mutation BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION adr020_reject_append_only_mutation();")
    op.execute(f"CREATE TRIGGER trg_{table}_append_only_truncate BEFORE TRUNCATE ON {table} FOR EACH STATEMENT EXECUTE FUNCTION adr020_reject_append_only_mutation();")

def upgrade():
    _require_postgresql()
    op.create_table("policy_activation_executions",
        S("policy_activation_execution_id", False), S("policy_decision_id"), S("policy_type"), S("policy_id"), sa.Column("policy_version", sa.Integer(), nullable=False), H("policy_hash"), S("authorization_basis_type"), S("authorization_class"), S("execution_mode"),
        S("bootstrap_authority_record_id", True), H("bootstrap_authority_record_hash", True), S("activation_authority_policy_id", True), sa.Column("activation_authority_policy_version", sa.Integer(), nullable=True), H("activation_authority_policy_hash", True), S("activation_authority_policy_activation_id", True), S("automation_envelope_id", True), sa.Column("automation_envelope_version", sa.Integer(), nullable=True), H("automation_envelope_hash", True), S("automation_envelope_activation_id", True),
        sa.Column("attempt_number", sa.Integer(), nullable=False), sa.Column("actor_or_worker", sa.String(255), nullable=False), S("lease_id"), sa.Column("fencing_token", sa.Integer(), nullable=False), sa.Column("idempotency_key", sa.String(255), nullable=False), S("state"), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("finished_at", sa.DateTime(timezone=True)), J("structured_result", True), J("structured_error", True), J("provenance"), H("record_hash"),
        sa.PrimaryKeyConstraint("policy_activation_execution_id"), sa.UniqueConstraint("idempotency_key", name="uq_policy_activation_executions_idempotency"), sa.UniqueConstraint("record_hash", name="uq_policy_activation_executions_record_hash"),
        sa.ForeignKeyConstraint(["policy_id","policy_version","policy_hash"],["policy_versions.policy_id","policy_versions.policy_version","policy_versions.policy_hash"],name="fk_policy_activation_executions_exact_policy",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["policy_decision_id"],["policy_decisions.decision_id"],name="fk_policy_activation_executions_exact_decision",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["bootstrap_authority_record_id"],["bootstrap_authority_records.bootstrap_authority_record_id"],name="fk_policy_activation_executions_exact_bootstrap",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["activation_authority_policy_id","activation_authority_policy_version","activation_authority_policy_hash"],["policy_versions.policy_id","policy_versions.policy_version","policy_versions.policy_hash"],name="fk_policy_activation_executions_exact_authority_policy",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["automation_envelope_id","automation_envelope_version","automation_envelope_hash"],["policy_versions.policy_id","policy_versions.policy_version","policy_versions.policy_hash"],name="fk_policy_activation_executions_exact_envelope",ondelete="RESTRICT"),
        sa.CheckConstraint("state IN ('pendente','em_execucao','concluida','falhada','cancelada')",name="ck_policy_activation_executions_state"), sa.CheckConstraint("authorization_basis_type IN ('bootstrap_authority_record','active_policy_chain')",name="ck_policy_activation_executions_basis"), sa.CheckConstraint("authorization_class IN ('constitucional_reservada','humana_delegada','automatica_delegada')",name="ck_policy_activation_executions_class"), sa.CheckConstraint("execution_mode IN ('manual','automatico')",name="ck_policy_activation_executions_mode"), sa.CheckConstraint("attempt_number > 0 AND fencing_token > 0",name="ck_policy_activation_executions_positive"), sa.CheckConstraint("policy_hash ~ '^[0-9a-f]{64}$' AND record_hash ~ '^[0-9a-f]{64}$'",name="ck_policy_activation_executions_sha256"))

    op.create_table("policy_activations", S("policy_activation_id",False), S("policy_activation_execution_id"), S("policy_decision_id"), S("policy_type"), S("policy_id"), sa.Column("policy_version",sa.Integer(),nullable=False), H("policy_hash"), sa.Column("domain",sa.String(255),nullable=False), S("modality"), J("operational_interval"), S("activation_generation_id"), sa.Column("activated_at",sa.DateTime(timezone=True),nullable=False), S("state"), sa.Column("technical_actor",sa.String(255),nullable=False), J("provenance"), H("record_hash"), sa.PrimaryKeyConstraint("policy_activation_id"), sa.UniqueConstraint("policy_activation_execution_id"), sa.UniqueConstraint("record_hash",name="uq_policy_activations_record_hash"), sa.ForeignKeyConstraint(["policy_activation_execution_id"],["policy_activation_executions.policy_activation_execution_id"],name="fk_policy_activations_execution",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["policy_decision_id"],["policy_decisions.decision_id"],name="fk_policy_activations_decision",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["policy_id","policy_version","policy_hash"],["policy_versions.policy_id","policy_versions.policy_version","policy_versions.policy_hash"],name="fk_policy_activations_exact_policy",ondelete="RESTRICT"), sa.CheckConstraint("state IN ('activa','suspensa','desactivada','expirada','revogada')",name="ck_policy_activations_state"), sa.CheckConstraint("policy_hash ~ '^[0-9a-f]{64}$' AND record_hash ~ '^[0-9a-f]{64}$'",name="ck_policy_activations_sha256"))
    op.create_foreign_key("fk_policy_activation_executions_exact_authority_activation","policy_activation_executions","policy_activations",["activation_authority_policy_activation_id"],["policy_activation_id"],ondelete="RESTRICT")
    op.create_foreign_key("fk_policy_activation_executions_exact_envelope_activation","policy_activation_executions","policy_activations",["automation_envelope_activation_id"],["policy_activation_id"],ondelete="RESTRICT")

    op.create_table("activation_decisions", S("activation_decision_id",False), S("decision_action"), S("decision_outcome"), S("authorization_class"), sa.Column("actor",sa.String(255),nullable=False), S("institutional_role"), J("target_scope"), H("scope_hash"), J("target_manifest"), H("target_manifest_hash"), J("authority_bindings"), J("policy_bindings"), J("coverage_binding"), J("continuity_binding"), J("precedence_binding"), J("gates_evidence"), sa.Column("rationale",sa.Text(),nullable=False), J("evidence"), S("previous_activation_decision_id",True), sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False,server_default=sa.text("now()")), sa.Column("idempotency_key",sa.String(255),nullable=False), H("record_hash"), sa.PrimaryKeyConstraint("activation_decision_id"), sa.UniqueConstraint("idempotency_key",name="uq_activation_decisions_idempotency"), sa.UniqueConstraint("record_hash",name="uq_activation_decisions_record_hash"), sa.UniqueConstraint("activation_decision_id","record_hash",name="uq_activation_decisions_exact"), sa.ForeignKeyConstraint(["previous_activation_decision_id"],["activation_decisions.activation_decision_id"],name="fk_activation_decisions_previous",ondelete="RESTRICT"), sa.CheckConstraint("decision_action IN ('activate','suspend','deactivate','expire','revoke')",name="ck_activation_decisions_action"), sa.CheckConstraint("decision_outcome IN ('approved','rejected','cancelled')",name="ck_activation_decisions_outcome"), sa.CheckConstraint("authorization_class IN ('constitucional_reservada','humana_delegada','automatica_delegada')",name="ck_activation_decisions_class"), sa.CheckConstraint("scope_hash ~ '^[0-9a-f]{64}$' AND target_manifest_hash ~ '^[0-9a-f]{64}$' AND record_hash ~ '^[0-9a-f]{64}$'",name="ck_activation_decisions_sha256"))

    op.create_table("activation_executions", S("activation_execution_id",False), S("activation_decision_id"), H("activation_decision_record_hash"), S("decision_outcome"), S("decision_action"), S("authorization_class"), S("execution_mode"), S("state"), H("scope_hash"), H("target_manifest_hash"), sa.Column("attempt_number",sa.Integer(),nullable=False), sa.Column("actor_or_worker",sa.String(255),nullable=False), S("lease_id"), sa.Column("fencing_token",sa.Integer(),nullable=False), sa.Column("idempotency_key",sa.String(255),nullable=False), J("authority_bindings"), J("policy_bindings"), J("coverage_binding"), J("continuity_binding"), J("precedence_binding"), J("gates_evidence"), sa.Column("started_at",sa.DateTime(timezone=True)), sa.Column("finished_at",sa.DateTime(timezone=True)), J("structured_result",True), J("structured_error",True), J("provenance"), H("record_hash"), sa.PrimaryKeyConstraint("activation_execution_id"), sa.UniqueConstraint("idempotency_key",name="uq_activation_executions_idempotency"), sa.UniqueConstraint("record_hash",name="uq_activation_executions_record_hash"), sa.ForeignKeyConstraint(["activation_decision_id","activation_decision_record_hash"],["activation_decisions.activation_decision_id","activation_decisions.record_hash"],name="fk_activation_executions_exact_decision",ondelete="RESTRICT"), sa.CheckConstraint("decision_outcome = 'approved'",name="ck_activation_executions_approved"), sa.CheckConstraint("state IN ('pending','running','completed','failed','cancelled')",name="ck_activation_executions_state"), sa.CheckConstraint("authorization_class <> 'constitucional_reservada' OR execution_mode = 'manual'",name="ck_activation_executions_reserved_manual"), sa.CheckConstraint("execution_mode <> 'automatico' OR authorization_class = 'automatica_delegada'",name="ck_activation_executions_automatic_class"), sa.CheckConstraint("attempt_number > 0 AND fencing_token > 0",name="ck_activation_executions_positive"))

    op.create_table("normative_activations", S("normative_activation_id",False), S("activation_decision_id"), H("activation_decision_record_hash"), S("activation_execution_id"), S("subject_type"), S("subject_id"), sa.Column("subject_version",sa.Integer(),nullable=False), H("subject_hash"), S("review_record_id"), H("review_record_hash"), sa.Column("domain",sa.String(255),nullable=False), S("modality"), J("resolver_scope"), J("operational_interval"), H("scope_hash"), S("activation_generation_id"), sa.Column("activated_at",sa.DateTime(timezone=True),nullable=False), S("state"), sa.Column("technical_actor",sa.String(255),nullable=False), J("provenance"), H("record_hash"), sa.PrimaryKeyConstraint("normative_activation_id"), sa.UniqueConstraint("record_hash",name="uq_normative_activations_record_hash"), sa.ForeignKeyConstraint(["activation_decision_id","activation_decision_record_hash"],["activation_decisions.activation_decision_id","activation_decisions.record_hash"],name="fk_normative_activations_exact_decision",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["activation_execution_id"],["activation_executions.activation_execution_id"],name="fk_normative_activations_execution",ondelete="RESTRICT"), sa.CheckConstraint("subject_type IN ('rule_version','normative_relation_version')",name="ck_normative_activations_subject_type"), sa.CheckConstraint("state IN ('active','suspended','deactivated','expired','revoked')",name="ck_normative_activations_state"))

    op.create_table("activation_generations", S("activation_generation_id",False), S("previous_activation_generation_id",True), H("previous_activation_generation_record_hash",True), S("activation_execution_id"), S("activation_decision_id"), H("activation_decision_record_hash"), H("target_manifest_hash"), J("scope_descriptor"), H("scope_hash"), J("composition_manifest"), H("composition_hash"), J("policy_bindings"), J("coverage_binding"), J("continuity_binding"), J("precedence_binding"), J("gates_evidence"), sa.Column("is_complete",sa.Boolean(),nullable=False), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.text("now()")), sa.Column("effective_from",sa.DateTime(timezone=True),nullable=False), J("provenance"), H("record_hash"), sa.PrimaryKeyConstraint("activation_generation_id"), sa.UniqueConstraint("activation_generation_id","record_hash",name="uq_activation_generations_exact"), sa.UniqueConstraint("activation_execution_id"), sa.UniqueConstraint("record_hash",name="uq_activation_generations_record_hash"), sa.UniqueConstraint("scope_hash","composition_hash",name="uq_activation_generations_content"), sa.ForeignKeyConstraint(["previous_activation_generation_id","previous_activation_generation_record_hash"],["activation_generations.activation_generation_id","activation_generations.record_hash"],name="fk_activation_generations_previous",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["activation_execution_id"],["activation_executions.activation_execution_id"],name="fk_activation_generations_execution",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["activation_decision_id","activation_decision_record_hash"],["activation_decisions.activation_decision_id","activation_decisions.record_hash"],name="fk_activation_generations_exact_decision",ondelete="RESTRICT"), sa.CheckConstraint("is_complete",name="ck_activation_generations_integral"))

    op.create_table("outbox_event_records", S("outbox_event_id",False), S("event_type"), S("activation_execution_id"), S("activation_generation_id"), S("activation_decision_id"), H("scope_hash"), H("composition_hash"), J("payload"), H("payload_hash"), J("provenance"), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.text("now()")), H("record_hash"), sa.PrimaryKeyConstraint("outbox_event_id"), sa.UniqueConstraint("record_hash",name="uq_outbox_event_records_record_hash"), sa.ForeignKeyConstraint(["activation_execution_id"],["activation_executions.activation_execution_id"],name="fk_outbox_event_records_execution",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["activation_generation_id"],["activation_generations.activation_generation_id"],name="fk_outbox_event_records_generation",ondelete="RESTRICT"), sa.ForeignKeyConstraint(["activation_decision_id"],["activation_decisions.activation_decision_id"],name="fk_outbox_event_records_decision",ondelete="RESTRICT"), sa.CheckConstraint("event_type IN ('activation_completed','activation_invalidated')",name="ck_outbox_event_records_type"), sa.CheckConstraint("scope_hash ~ '^[0-9a-f]{64}$' AND composition_hash ~ '^[0-9a-f]{64}$' AND payload_hash ~ '^[0-9a-f]{64}$' AND record_hash ~ '^[0-9a-f]{64}$'",name="ck_outbox_event_records_sha256"))

    op.execute("""CREATE FUNCTION adr020_validate_atomic_activation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
      IF TG_TABLE_NAME = 'activation_executions' AND NEW.decision_outcome <> 'approved' THEN RAISE EXCEPTION 'ADR-020 only approved decision is executable'; END IF;
      IF TG_TABLE_NAME = 'activation_generations' AND NOT NEW.is_complete THEN RAISE EXCEPTION 'ADR-020 partial generation forbidden'; END IF;
      RETURN NEW; END; $$;""")
    for table in ("activation_executions","activation_generations"): op.execute(f"CREATE TRIGGER trg_{table}_validate_insert BEFORE INSERT ON {table} FOR EACH ROW EXECUTE FUNCTION adr020_validate_atomic_activation();")
    for table in TABLES: _append_only(table)

def downgrade():
    raise RuntimeError("Migration 0024_adr020_activation is irreversible by ratified ADR-020 append-only requirements")
