"""ADR-020 credential and sanitization chain (PostgreSQL only)."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0025_adr020_credentials"
down_revision = "0024_adr020_activation"
branch_labels = None
depends_on = None

TABLES = ("credential_binding_versions", "credential_lifecycle_event_records", "secret_access_execution_records", "credential_use_records", "sanitized_acquisition_receipts", "sanitization_verification_records")

def S(name, nullable=False): return sa.Column(name, sa.String(255), nullable=nullable)
def I(name, nullable=False): return sa.Column(name, sa.Integer(), nullable=nullable)
def T(name, nullable=False): return sa.Column(name, sa.DateTime(timezone=True), nullable=nullable)
def J(name, nullable=False): return sa.Column(name, postgresql.JSONB(astext_type=sa.Text()), nullable=nullable)
def B(name, nullable=False): return sa.Column(name, sa.Boolean(), nullable=nullable)
def _append_only(table):
    op.execute(f"CREATE TRIGGER trg_{table}_append_only_mutation BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION adr020_reject_append_only_mutation();")
    op.execute(f"CREATE TRIGGER trg_{table}_append_only_truncate BEFORE TRUNCATE ON {table} FOR EACH STATEMENT EXECUTE FUNCTION adr020_reject_append_only_mutation();")

def upgrade():
    if op.get_bind().dialect.name != "postgresql": raise RuntimeError("Migration 0025_adr020_credentials is PostgreSQL-only")
    op.create_table("credential_binding_versions", S("credential_binding_id"), I("credential_binding_version"), S("credential_binding_hash"), S("credential_type"), J("secret_provider_binding"), S("opaque_secret_reference_id"), S("opaque_secret_version_reference_id"), S("permitted_purpose"), S("permitted_operation"), J("permitted_source_scope"), J("permitted_tenant_scope", True), J("acquisition_contract_binding"), J("secret_access_policy_binding"), J("security_policy_binding"), J("sanitization_policy_binding"), T("valid_from"), T("valid_until", True), T("created_at"), S("creator"), J("provenance"), S("record_hash"), sa.PrimaryKeyConstraint("credential_binding_id", "credential_binding_version"), sa.UniqueConstraint("credential_binding_id", "credential_binding_version", "credential_binding_hash"), sa.CheckConstraint("credential_binding_version > 0 AND (valid_until IS NULL OR valid_until > valid_from)"), sa.CheckConstraint("credential_binding_hash ~ '^[0-9a-f]{64}$' AND record_hash ~ '^[0-9a-f]{64}$'"))
    op.create_table("credential_lifecycle_event_records", S("credential_lifecycle_event_record_id"), S("credential_binding_id"), I("credential_binding_version"), S("credential_binding_hash"), S("lifecycle_event"), S("previous_lifecycle_event_record_id", True), S("previous_lifecycle_event_record_hash", True), S("replacement_credential_binding_id", True), I("replacement_credential_binding_version", True), S("replacement_credential_binding_hash", True), T("effective_at"), S("actor"), S("institutional_role"), S("reason_code"), J("provenance"), S("record_hash"), sa.PrimaryKeyConstraint("credential_lifecycle_event_record_id"), sa.UniqueConstraint("credential_lifecycle_event_record_id", "record_hash"), sa.UniqueConstraint("previous_lifecycle_event_record_id"), sa.ForeignKeyConstraint(["credential_binding_id","credential_binding_version","credential_binding_hash"],["credential_binding_versions.credential_binding_id","credential_binding_versions.credential_binding_version","credential_binding_versions.credential_binding_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["previous_lifecycle_event_record_id","previous_lifecycle_event_record_hash"],["credential_lifecycle_event_records.credential_lifecycle_event_record_id","credential_lifecycle_event_records.record_hash"],ondelete="RESTRICT"), sa.CheckConstraint("lifecycle_event IN ('activated','suspended','resumed','revoked','expired','rotated')"))
    op.create_table("secret_access_execution_records", S("secret_access_execution_record_id"), S("acquisition_execution_id"), S("acquisition_execution_record_hash"), S("credential_binding_id"), I("credential_binding_version"), S("credential_binding_hash"), S("credential_lifecycle_event_record_id"), S("credential_lifecycle_event_record_hash"), S("secret_provider_id"), I("secret_provider_version"), S("secret_provider_artifact_hash"), S("opaque_secret_reference_id"), S("opaque_secret_version_reference_id"), S("requested_purpose"), S("requested_operation"), J("requested_source_scope"), J("requested_tenant_scope", True), I("attempt_number"), S("actor_or_worker"), S("lease_id"), S("lease_record_hash"), I("fencing_token"), S("access_state"), T("started_at"), T("finished_at", True), J("structured_result", True), J("structured_error", True), J("provenance"), S("record_hash"), sa.PrimaryKeyConstraint("secret_access_execution_record_id"), sa.UniqueConstraint("secret_access_execution_record_id","record_hash"), sa.ForeignKeyConstraint(["credential_binding_id","credential_binding_version","credential_binding_hash"],["credential_binding_versions.credential_binding_id","credential_binding_versions.credential_binding_version","credential_binding_versions.credential_binding_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["credential_lifecycle_event_record_id","credential_lifecycle_event_record_hash"],["credential_lifecycle_event_records.credential_lifecycle_event_record_id","credential_lifecycle_event_records.record_hash"],ondelete="RESTRICT"), sa.CheckConstraint("access_state IN ('pending','validating','authorized','accessed','rejected_inactive','rejected_scope','rejected_policy','rejected_divergent','failed','cancelled')"), sa.CheckConstraint("attempt_number > 0 AND fencing_token > 0"))
    use_cols = [S("credential_use_record_id"),S("credential_use_chain_id"),S("previous_credential_use_record_id",True),S("previous_credential_use_record_hash",True),S("acquisition_execution_id"),S("acquisition_execution_record_hash"),S("secret_access_execution_record_id"),S("secret_access_execution_record_hash"),S("credential_binding_id"),I("credential_binding_version"),S("credential_binding_hash"),S("credential_lifecycle_event_record_id"),S("credential_lifecycle_event_record_hash"),S("request_contract_id"),I("request_contract_version"),S("request_contract_hash"),S("sanitized_request_fingerprint"),I("sanitized_request_fingerprint_schema_version"),S("sanitized_request_canonicalization_contract_id"),I("sanitized_request_canonicalization_contract_version"),S("sanitized_request_canonicalization_contract_hash"),J("source_scope"),J("tenant_scope",True),I("dispatch_attempt_number"),T("dispatched_at",True),T("finished_at"),S("use_outcome"),B("source_response_observed"),J("structured_result",True),J("structured_error",True),J("provenance"),S("record_hash")]
    op.create_table("credential_use_records", *use_cols, sa.PrimaryKeyConstraint("credential_use_record_id"), sa.UniqueConstraint("credential_use_record_id","record_hash"), sa.UniqueConstraint("previous_credential_use_record_id"), sa.ForeignKeyConstraint(["secret_access_execution_record_id","secret_access_execution_record_hash"],["secret_access_execution_records.secret_access_execution_record_id","secret_access_execution_records.record_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["previous_credential_use_record_id","previous_credential_use_record_hash"],["credential_use_records.credential_use_record_id","credential_use_records.record_hash"],ondelete="RESTRICT"), sa.CheckConstraint("use_outcome IN ('dispatched','succeeded','rejected_by_source','transport_failed','cancelled_before_dispatch','indeterminate_after_dispatch')"))
    receipt_cols = [S("sanitized_acquisition_receipt_id"),I("sanitized_acquisition_receipt_schema_version"),S("sanitized_acquisition_receipt_hash"),S("acquisition_execution_id"),S("acquisition_execution_record_hash"),S("credential_use_record_id"),S("credential_use_record_hash"),S("credential_binding_id"),I("credential_binding_version"),S("credential_binding_hash"),J("source_identity_binding"),J("source_scope"),J("tenant_scope",True),S("request_contract_id"),I("request_contract_version"),S("request_contract_hash"),J("sanitized_request_manifest"),S("sanitized_request_fingerprint"),I("sanitized_request_fingerprint_schema_version"),S("sanitized_request_canonicalization_contract_id"),I("sanitized_request_canonicalization_contract_version"),S("sanitized_request_canonicalization_contract_hash"),S("response_status_class",True),J("sanitized_response_metadata"),J("acquired_content_reference",True),S("acquired_content_hash",True),J("transport_evidence_manifest"),J("redaction_manifest"),J("sanitization_policy_binding"),T("acquisition_started_at"),T("dispatch_observed_at",True),T("response_observed_at",True),T("receipt_created_at"),S("acquisition_outcome"),S("creator"),J("provenance"),S("record_hash")]
    op.create_table("sanitized_acquisition_receipts", *receipt_cols, sa.PrimaryKeyConstraint("sanitized_acquisition_receipt_id"), sa.UniqueConstraint("sanitized_acquisition_receipt_id","sanitized_acquisition_receipt_hash"), sa.ForeignKeyConstraint(["credential_use_record_id","credential_use_record_hash"],["credential_use_records.credential_use_record_id","credential_use_records.record_hash"],ondelete="RESTRICT"), sa.CheckConstraint("acquisition_outcome IN ('acquired','source_rejected','no_content_valid','transport_failed','indeterminate','cancelled_before_dispatch')"))
    op.create_table("sanitization_verification_records", S("sanitization_verification_record_id"),S("sanitized_acquisition_receipt_id"),S("sanitized_acquisition_receipt_hash"),S("sanitization_policy_id"),I("sanitization_policy_version"),S("sanitization_policy_hash"),S("sanitization_policy_activation_id"),S("sanitization_policy_activation_record_hash"),S("verification_engine_id"),I("verification_engine_version"),S("verification_engine_hash"),J("inspected_component_manifest"),J("violation_manifest"),S("verification_outcome"),T("verified_at"),S("verifier"),J("provenance"),S("record_hash"),sa.PrimaryKeyConstraint("sanitization_verification_record_id"),sa.ForeignKeyConstraint(["sanitized_acquisition_receipt_id","sanitized_acquisition_receipt_hash"],["sanitized_acquisition_receipts.sanitized_acquisition_receipt_id","sanitized_acquisition_receipts.sanitized_acquisition_receipt_hash"],ondelete="RESTRICT"),sa.CheckConstraint("verification_outcome IN ('verified_sanitized','verified_violation','inconclusive')"))
    op.execute("""CREATE FUNCTION adr020_validate_credential_chain() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
      IF TG_TABLE_NAME='secret_access_execution_records' AND NEW.access_state IN ('authorized','accessed') AND NOT EXISTS (SELECT 1 FROM credential_lifecycle_event_records l WHERE l.credential_lifecycle_event_record_id=NEW.credential_lifecycle_event_record_id AND l.record_hash=NEW.credential_lifecycle_event_record_hash AND l.lifecycle_event IN ('activated','resumed')) THEN RAISE EXCEPTION 'ADR-020 inactive binding'; END IF;
      IF TG_TABLE_NAME='credential_use_records' AND NOT EXISTS (SELECT 1 FROM secret_access_execution_records a WHERE a.secret_access_execution_record_id=NEW.secret_access_execution_record_id AND a.record_hash=NEW.secret_access_execution_record_hash AND a.access_state IN ('authorized','accessed')) THEN RAISE EXCEPTION 'ADR-020 favorable access required'; END IF;
      IF TG_TABLE_NAME='sanitization_verification_records' AND NEW.verification_outcome='verified_sanitized' AND (COALESCE((NEW.inspected_component_manifest->>'complete')::boolean,false)=false OR jsonb_array_length(NEW.violation_manifest)<>0) THEN RAISE EXCEPTION 'ADR-020 partial verification forbidden'; END IF;
      RETURN NEW; END $$;""")
    for table in ("secret_access_execution_records","credential_use_records","sanitization_verification_records"): op.execute(f"CREATE TRIGGER trg_{table}_validate_insert BEFORE INSERT ON {table} FOR EACH ROW EXECUTE FUNCTION adr020_validate_credential_chain();")
    op.execute("""CREATE FUNCTION adr020_require_sanitized_acquisition() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
      IF TG_TABLE_NAME='acquisition_executions' AND NEW.projected_state='concluida' AND NOT EXISTS (SELECT 1 FROM sanitized_acquisition_receipts r JOIN sanitization_verification_records v ON v.sanitized_acquisition_receipt_id=r.sanitized_acquisition_receipt_id AND v.sanitized_acquisition_receipt_hash=r.sanitized_acquisition_receipt_hash WHERE r.acquisition_execution_id=NEW.acquisition_execution_id AND v.verification_outcome='verified_sanitized') THEN RAISE EXCEPTION 'ADR-020 verified sanitized receipt required'; END IF;
      IF TG_TABLE_NAME='extraction_runs' AND NOT EXISTS (SELECT 1 FROM sanitized_acquisition_receipts r JOIN sanitization_verification_records v ON v.sanitized_acquisition_receipt_id=r.sanitized_acquisition_receipt_id AND v.sanitized_acquisition_receipt_hash=r.sanitized_acquisition_receipt_hash WHERE r.acquisition_execution_id=NEW.acquisition_execution_id AND v.verification_outcome='verified_sanitized') THEN RAISE EXCEPTION 'ADR-020 verified sanitized receipt required before extraction'; END IF;
      RETURN NEW; END $$;""")
    op.execute("CREATE TRIGGER trg_acquisition_executions_require_sanitized BEFORE INSERT ON acquisition_executions FOR EACH ROW EXECUTE FUNCTION adr020_require_sanitized_acquisition();")
    op.execute("CREATE TRIGGER trg_extraction_runs_require_sanitized BEFORE INSERT ON extraction_runs FOR EACH ROW EXECUTE FUNCTION adr020_require_sanitized_acquisition();")
    for table in TABLES: _append_only(table)

def downgrade():
    raise RuntimeError("Migration 0025_adr020_credentials is irreversible by ratified ADR-020 append-only requirements")
