"""ADR-020 generation consumption and replica fences (PostgreSQL only)."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0026_adr020_consumption"
down_revision = "0025_adr020_credentials"
branch_labels = None
depends_on = None

TABLES = ("generation_fence_records", "consumer_contract_versions", "consumer_application_records", "replica_checkpoint_records")

def S(name, nullable=False): return sa.Column(name, sa.String(255), nullable=nullable)
def I(name, nullable=False): return sa.Column(name, sa.Integer(), nullable=nullable)
def T(name, nullable=False): return sa.Column(name, sa.DateTime(timezone=True), nullable=nullable)
def J(name, nullable=False): return sa.Column(name, postgresql.JSONB(astext_type=sa.Text()), nullable=nullable)
def _append_only(table):
    op.execute(f"CREATE TRIGGER trg_{table}_append_only_mutation BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION adr020_reject_append_only_mutation();")
    op.execute(f"CREATE TRIGGER trg_{table}_append_only_truncate BEFORE TRUNCATE ON {table} FOR EACH STATEMENT EXECUTE FUNCTION adr020_reject_append_only_mutation();")

def upgrade():
    if op.get_bind().dialect.name != "postgresql": raise RuntimeError("Migration 0026_adr020_consumption is PostgreSQL-only")
    op.create_unique_constraint(
        "uq_activation_executions_exact",
        "activation_executions",
        ["activation_execution_id", "record_hash"],
    )
    op.create_unique_constraint(
        "uq_outbox_event_records_exact",
        "outbox_event_records",
        ["outbox_event_id", "record_hash"],
    )
    op.create_table("generation_fence_records", S("generation_fence_record_id"), S("scope_hash"), I("generation_sequence"), I("fencing_token"), S("activation_generation_id"), S("activation_generation_record_hash"), S("activation_execution_id"), S("activation_execution_record_hash"), S("publisher_lease_id"), S("publisher_lease_record_hash"), S("composition_hash"), S("previous_generation_fence_record_id", True), S("previous_generation_fence_record_hash", True), S("source_event_id"), S("source_event_record_hash"), T("published_at"), S("publisher"), J("provenance"), S("record_hash"), sa.PrimaryKeyConstraint("generation_fence_record_id"), sa.UniqueConstraint("generation_fence_record_id", "record_hash"), sa.UniqueConstraint("scope_hash", "generation_sequence"), sa.UniqueConstraint("scope_hash", "fencing_token"), sa.UniqueConstraint("previous_generation_fence_record_id"), sa.ForeignKeyConstraint(["activation_generation_id","activation_generation_record_hash"],["activation_generations.activation_generation_id","activation_generations.record_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["activation_execution_id","activation_execution_record_hash"],["activation_executions.activation_execution_id","activation_executions.record_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["previous_generation_fence_record_id","previous_generation_fence_record_hash"],["generation_fence_records.generation_fence_record_id","generation_fence_records.record_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["source_event_id","source_event_record_hash"],["outbox_event_records.outbox_event_id","outbox_event_records.record_hash"],ondelete="RESTRICT"), sa.CheckConstraint("generation_sequence > 0 AND fencing_token > 0"), sa.CheckConstraint("scope_hash ~ '^[0-9a-f]{64}$' AND activation_generation_record_hash ~ '^[0-9a-f]{64}$' AND activation_execution_record_hash ~ '^[0-9a-f]{64}$' AND publisher_lease_record_hash ~ '^[0-9a-f]{64}$' AND composition_hash ~ '^[0-9a-f]{64}$' AND source_event_record_hash ~ '^[0-9a-f]{64}$' AND record_hash ~ '^[0-9a-f]{64}$'"))
    op.create_table("consumer_contract_versions", S("consumer_id"), I("consumer_contract_version"), S("consumer_contract_hash"), S("consumer_type"), I("supported_protocol_version"), I("supported_generation_schema_version"), J("allowed_scope_descriptor"), S("allowed_scope_hash"), J("compatibility_rules"), J("freshness_policy_binding"), J("security_policy_binding"), T("created_at"), J("provenance"), S("record_hash"), sa.PrimaryKeyConstraint("consumer_id", "consumer_contract_version"), sa.UniqueConstraint("consumer_id", "consumer_contract_version", "consumer_contract_hash"), sa.UniqueConstraint("record_hash"), sa.CheckConstraint("consumer_contract_version > 0 AND supported_protocol_version > 0 AND supported_generation_schema_version > 0"), sa.CheckConstraint("consumer_type IN ('service','replica','batch','interactive')"), sa.CheckConstraint("consumer_contract_hash ~ '^[0-9a-f]{64}$' AND allowed_scope_hash ~ '^[0-9a-f]{64}$' AND record_hash ~ '^[0-9a-f]{64}$'"))
    app_cols = [S("consumer_application_record_id"),S("consumer_id"),S("replica_id"),S("replica_instance_id"),I("consumer_contract_version"),S("consumer_contract_hash"),S("scope_hash"),S("generation_fence_record_id"),S("generation_fence_record_hash"),I("generation_sequence"),I("fencing_token"),S("activation_generation_id"),S("activation_generation_record_hash"),S("composition_hash"),S("previous_replica_checkpoint_record_id",True),S("previous_replica_checkpoint_record_hash",True),S("duplicate_of_consumer_application_record_id",True),S("duplicate_of_consumer_application_record_hash",True),S("duplicate_of_replica_checkpoint_record_id",True),S("duplicate_of_replica_checkpoint_record_hash",True),I("attempt_number"),S("application_result"),T("started_at"),T("finished_at",True),J("structured_result",True),J("structured_error",True),J("provenance"),S("record_hash")]
    op.create_table("consumer_application_records", *app_cols, sa.PrimaryKeyConstraint("consumer_application_record_id"), sa.UniqueConstraint("consumer_application_record_id","record_hash"), sa.UniqueConstraint("consumer_id","replica_id","replica_instance_id","attempt_number"), sa.ForeignKeyConstraint(["consumer_id","consumer_contract_version","consumer_contract_hash"],["consumer_contract_versions.consumer_id","consumer_contract_versions.consumer_contract_version","consumer_contract_versions.consumer_contract_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["generation_fence_record_id","generation_fence_record_hash"],["generation_fence_records.generation_fence_record_id","generation_fence_records.record_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["activation_generation_id","activation_generation_record_hash"],["activation_generations.activation_generation_id","activation_generations.record_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["duplicate_of_consumer_application_record_id","duplicate_of_consumer_application_record_hash"],["consumer_application_records.consumer_application_record_id","consumer_application_records.record_hash"],ondelete="RESTRICT"), sa.CheckConstraint("attempt_number > 0 AND generation_sequence > 0 AND fencing_token > 0"), sa.CheckConstraint("application_result IN ('pending','validating','applied','duplicate_exact','rejected_stale','rejected_gap','rejected_divergent','rejected_incompatible','failed','cancelled')"))
    checkpoint_cols = [S("replica_checkpoint_record_id"),S("consumer_application_record_id"),S("consumer_application_record_hash"),S("consumer_id"),S("replica_id"),S("replica_instance_id"),I("consumer_contract_version"),S("consumer_contract_hash"),S("scope_hash"),S("generation_fence_record_id"),S("generation_fence_record_hash"),I("generation_sequence"),I("fencing_token"),S("activation_generation_id"),S("activation_generation_record_hash"),S("composition_hash"),S("previous_replica_checkpoint_record_id",True),S("previous_replica_checkpoint_record_hash",True),T("applied_at"),J("provenance"),S("record_hash")]
    op.create_table("replica_checkpoint_records", *checkpoint_cols, sa.PrimaryKeyConstraint("replica_checkpoint_record_id"), sa.UniqueConstraint("replica_checkpoint_record_id","record_hash"), sa.UniqueConstraint("consumer_application_record_id"), sa.UniqueConstraint("previous_replica_checkpoint_record_id"), sa.UniqueConstraint("consumer_id","replica_id","replica_instance_id","scope_hash","generation_sequence"), sa.ForeignKeyConstraint(["consumer_application_record_id","consumer_application_record_hash"],["consumer_application_records.consumer_application_record_id","consumer_application_records.record_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["consumer_id","consumer_contract_version","consumer_contract_hash"],["consumer_contract_versions.consumer_id","consumer_contract_versions.consumer_contract_version","consumer_contract_versions.consumer_contract_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["generation_fence_record_id","generation_fence_record_hash"],["generation_fence_records.generation_fence_record_id","generation_fence_records.record_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["activation_generation_id","activation_generation_record_hash"],["activation_generations.activation_generation_id","activation_generations.record_hash"],ondelete="RESTRICT"), sa.ForeignKeyConstraint(["previous_replica_checkpoint_record_id","previous_replica_checkpoint_record_hash"],["replica_checkpoint_records.replica_checkpoint_record_id","replica_checkpoint_records.record_hash"],ondelete="RESTRICT"), sa.CheckConstraint("generation_sequence > 0 AND fencing_token > 0"))
    op.create_foreign_key("fk_consumer_applications_exact_previous_checkpoint", "consumer_application_records", "replica_checkpoint_records", ["previous_replica_checkpoint_record_id","previous_replica_checkpoint_record_hash"], ["replica_checkpoint_record_id","record_hash"], ondelete="RESTRICT")
    op.create_foreign_key("fk_consumer_applications_exact_duplicate_checkpoint", "consumer_application_records", "replica_checkpoint_records", ["duplicate_of_replica_checkpoint_record_id","duplicate_of_replica_checkpoint_record_hash"], ["replica_checkpoint_record_id","record_hash"], ondelete="RESTRICT")
    op.execute("""CREATE FUNCTION adr020_validate_consumption_chain() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE p generation_fence_records%ROWTYPE; a consumer_application_records%ROWTYPE; g activation_generations%ROWTYPE; e activation_executions%ROWTYPE; BEGIN
      IF TG_TABLE_NAME='generation_fence_records' THEN SELECT * INTO g FROM activation_generations WHERE activation_generation_id=NEW.activation_generation_id AND record_hash=NEW.activation_generation_record_hash; SELECT * INTO e FROM activation_executions WHERE activation_execution_id=NEW.activation_execution_id AND record_hash=NEW.activation_execution_record_hash; IF NOT FOUND OR NOT g.is_complete OR e.state<>'completed' OR g.activation_execution_id<>NEW.activation_execution_id OR g.scope_hash<>NEW.scope_hash OR g.composition_hash<>NEW.composition_hash THEN RAISE EXCEPTION 'ADR-020 exact integral generation and completed execution required'; END IF; IF NEW.previous_generation_fence_record_id IS NULL THEN IF NEW.generation_sequence<>1 THEN RAISE EXCEPTION 'ADR-020 first fence sequence must be 1'; END IF; ELSE SELECT * INTO p FROM generation_fence_records WHERE generation_fence_record_id=NEW.previous_generation_fence_record_id AND record_hash=NEW.previous_generation_fence_record_hash AND scope_hash=NEW.scope_hash; IF NOT FOUND OR NEW.generation_sequence<>p.generation_sequence+1 OR NEW.fencing_token<=p.fencing_token THEN RAISE EXCEPTION 'ADR-020 fence gap, divergence or stale token'; END IF; END IF;
      ELSIF TG_TABLE_NAME='consumer_application_records' THEN IF NEW.application_result='applied' AND (NEW.structured_result IS NULL OR COALESCE((NEW.structured_result->>'application_complete')::boolean,false)=false) THEN RAISE EXCEPTION 'ADR-020 partial application forbidden'; END IF; IF NEW.application_result='duplicate_exact' AND (NEW.duplicate_of_consumer_application_record_id IS NULL OR NEW.duplicate_of_replica_checkpoint_record_id IS NULL) THEN RAISE EXCEPTION 'ADR-020 exact duplicate references required'; END IF; IF NOT EXISTS (SELECT 1 FROM generation_fence_records f JOIN consumer_contract_versions c ON c.consumer_id=NEW.consumer_id AND c.consumer_contract_version=NEW.consumer_contract_version AND c.consumer_contract_hash=NEW.consumer_contract_hash WHERE f.generation_fence_record_id=NEW.generation_fence_record_id AND f.record_hash=NEW.generation_fence_record_hash AND f.scope_hash=NEW.scope_hash AND f.generation_sequence=NEW.generation_sequence AND f.fencing_token=NEW.fencing_token AND f.activation_generation_id=NEW.activation_generation_id AND f.activation_generation_record_hash=NEW.activation_generation_record_hash AND f.composition_hash=NEW.composition_hash AND c.allowed_scope_hash=NEW.scope_hash) THEN RAISE EXCEPTION 'ADR-020 incompatible contract, fence or generation'; END IF;
      ELSE SELECT * INTO a FROM consumer_application_records WHERE consumer_application_record_id=NEW.consumer_application_record_id AND record_hash=NEW.consumer_application_record_hash; IF NOT FOUND OR a.application_result<>'applied' OR COALESCE((a.structured_result->>'application_complete')::boolean,false)=false OR (a.consumer_id,a.replica_id,a.replica_instance_id,a.consumer_contract_version,a.consumer_contract_hash,a.scope_hash,a.generation_fence_record_id,a.generation_fence_record_hash,a.generation_sequence,a.fencing_token,a.activation_generation_id,a.activation_generation_record_hash,a.composition_hash)<>(NEW.consumer_id,NEW.replica_id,NEW.replica_instance_id,NEW.consumer_contract_version,NEW.consumer_contract_hash,NEW.scope_hash,NEW.generation_fence_record_id,NEW.generation_fence_record_hash,NEW.generation_sequence,NEW.fencing_token,NEW.activation_generation_id,NEW.activation_generation_record_hash,NEW.composition_hash) THEN RAISE EXCEPTION 'ADR-020 divergent or partial replica checkpoint'; END IF; IF NEW.previous_replica_checkpoint_record_id IS NULL AND NEW.generation_sequence<>1 THEN RAISE EXCEPTION 'ADR-020 first checkpoint must be sequence 1'; END IF; IF NEW.previous_replica_checkpoint_record_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM replica_checkpoint_records r WHERE r.replica_checkpoint_record_id=NEW.previous_replica_checkpoint_record_id AND r.record_hash=NEW.previous_replica_checkpoint_record_hash AND r.consumer_id=NEW.consumer_id AND r.replica_id=NEW.replica_id AND r.replica_instance_id=NEW.replica_instance_id AND r.scope_hash=NEW.scope_hash AND NEW.generation_sequence=r.generation_sequence+1) THEN RAISE EXCEPTION 'ADR-020 replica gap or divergence'; END IF; END IF; RETURN NEW; END $$;""")
    for table in TABLES: op.execute(f"CREATE TRIGGER trg_{table}_validate_insert BEFORE INSERT ON {table} FOR EACH ROW EXECUTE FUNCTION adr020_validate_consumption_chain();"); _append_only(table)

def downgrade():
    raise RuntimeError("Migration 0026_adr020_consumption is irreversible by ratified ADR-020 append-only requirements")
