"""ADR-020 BC-3B deterministic calculation and replay (PostgreSQL-only)."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0027_adr020_calc_replay"
down_revision = "0026_adr020_consumption"
branch_labels = None
depends_on = None

TABLES = ("calculation_bundles", "calculation_execution_records", "calculation_result_records", "replay_execution_records", "replay_verification_records")


def S(name, nullable=False): return sa.Column(name, sa.String(255), nullable=nullable)
def I(name): return sa.Column(name, sa.Integer(), nullable=False)
def B(name): return sa.Column(name, sa.Boolean(), nullable=False)
def T(name, nullable=False): return sa.Column(name, sa.DateTime(timezone=True), nullable=nullable)
def J(name, nullable=False): return sa.Column(name, postgresql.JSONB(astext_type=sa.Text()), nullable=nullable)


def _append_only(table):
    op.execute(f"CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION adr020_reject_append_only_mutation()")
    op.execute(f"CREATE TRIGGER trg_{table}_truncate BEFORE TRUNCATE ON {table} FOR EACH STATEMENT EXECUTE FUNCTION adr020_reject_append_only_mutation()")


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name != "postgresql": raise RuntimeError("ADR-020 calculation/replay migration is PostgreSQL-only")
    hashes = "calculation_bundle_hash ~ '^[0-9a-f]{64}$' AND scope_hash ~ '^[0-9a-f]{64}$' AND generation_fence_record_hash ~ '^[0-9a-f]{64}$' AND activation_generation_record_hash ~ '^[0-9a-f]{64}$' AND composition_hash ~ '^[0-9a-f]{64}$' AND consumer_contract_hash ~ '^[0-9a-f]{64}$' AND consumer_application_record_hash ~ '^[0-9a-f]{64}$' AND replica_checkpoint_record_hash ~ '^[0-9a-f]{64}$' AND record_hash ~ '^[0-9a-f]{64}$'"
    op.create_table("calculation_bundles", S("calculation_bundle_id"),I("calculation_bundle_schema_version"),S("calculation_bundle_hash"),S("scope_hash"),S("generation_fence_record_id"),S("generation_fence_record_hash"),I("generation_sequence"),I("fencing_token"),S("activation_generation_id"),S("activation_generation_record_hash"),S("composition_hash"),S("consumer_id"),I("consumer_contract_version"),S("consumer_contract_hash"),S("replica_id"),S("replica_instance_id"),S("consumer_application_record_id"),S("consumer_application_record_hash"),S("replica_checkpoint_record_id"),S("replica_checkpoint_record_hash"),J("calculation_subject_reference"),J("input_snapshot_manifest"),J("normative_member_manifest"),J("policy_binding_manifest"),J("coverage_binding"),J("continuity_binding"),J("precedence_binding"),J("gates_evidence"),J("engine_binding"),J("runtime_binding"),J("canonical_serialization_binding"),T("evaluation_instant"),J("deterministic_seed_binding"),T("created_at"),S("creator"),J("provenance"),S("record_hash"),sa.PrimaryKeyConstraint("calculation_bundle_id"),sa.UniqueConstraint("calculation_bundle_id","calculation_bundle_hash"),sa.UniqueConstraint("record_hash"),sa.ForeignKeyConstraint(["generation_fence_record_id","generation_fence_record_hash"],["generation_fence_records.generation_fence_record_id","generation_fence_records.record_hash"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["activation_generation_id","activation_generation_record_hash"],["activation_generations.activation_generation_id","activation_generations.record_hash"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["consumer_id","consumer_contract_version","consumer_contract_hash"],["consumer_contract_versions.consumer_id","consumer_contract_versions.consumer_contract_version","consumer_contract_versions.consumer_contract_hash"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["consumer_application_record_id","consumer_application_record_hash"],["consumer_application_records.consumer_application_record_id","consumer_application_records.record_hash"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["replica_checkpoint_record_id","replica_checkpoint_record_hash"],["replica_checkpoint_records.replica_checkpoint_record_id","replica_checkpoint_records.record_hash"],ondelete="RESTRICT"),sa.CheckConstraint("calculation_bundle_schema_version > 0 AND generation_sequence > 0 AND fencing_token > 0"),sa.CheckConstraint(hashes))
    op.create_table("calculation_execution_records",S("calculation_execution_record_id"),S("calculation_bundle_id"),S("calculation_bundle_hash"),I("attempt_number"),I("fencing_token"),S("state"),S("executor"),S("engine_artifact_id"),S("engine_artifact_hash"),S("runtime_artifact_id"),S("runtime_artifact_hash"),T("started_at"),T("finished_at",True),J("structured_result",True),J("structured_error",True),J("provenance"),S("record_hash"),sa.PrimaryKeyConstraint("calculation_execution_record_id"),sa.UniqueConstraint("calculation_execution_record_id","record_hash"),sa.UniqueConstraint("calculation_bundle_id","attempt_number"),sa.ForeignKeyConstraint(["calculation_bundle_id","calculation_bundle_hash"],["calculation_bundles.calculation_bundle_id","calculation_bundles.calculation_bundle_hash"],ondelete="RESTRICT"),sa.CheckConstraint("attempt_number > 0 AND fencing_token > 0"),sa.CheckConstraint("state IN ('pending','validating','running','completed','rejected_incomplete','rejected_divergent','rejected_incompatible','failed','cancelled')"))
    op.create_table("calculation_result_records",S("calculation_result_record_id"),S("calculation_execution_record_id"),S("calculation_execution_record_hash"),S("calculation_bundle_id"),S("calculation_bundle_hash"),I("result_schema_version"),J("result_payload_reference"),S("result_payload_hash"),J("calculation_trace_reference"),S("calculation_trace_hash"),J("decision_trace_reference"),S("decision_trace_hash"),S("canonical_result_hash"),T("completed_at"),J("provenance"),S("record_hash"),sa.PrimaryKeyConstraint("calculation_result_record_id"),sa.UniqueConstraint("calculation_result_record_id","record_hash"),sa.UniqueConstraint("calculation_execution_record_id"),sa.ForeignKeyConstraint(["calculation_execution_record_id","calculation_execution_record_hash"],["calculation_execution_records.calculation_execution_record_id","calculation_execution_records.record_hash"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["calculation_bundle_id","calculation_bundle_hash"],["calculation_bundles.calculation_bundle_id","calculation_bundles.calculation_bundle_hash"],ondelete="RESTRICT"),sa.CheckConstraint("result_schema_version > 0"))
    op.create_table("replay_execution_records",S("replay_execution_record_id"),S("calculation_bundle_id"),S("calculation_bundle_hash"),S("original_calculation_execution_record_id"),S("original_calculation_execution_record_hash"),S("original_calculation_result_record_id"),S("original_calculation_result_record_hash"),S("original_canonical_result_hash"),S("replay_engine_artifact_id"),S("replay_engine_artifact_hash"),S("replay_runtime_artifact_id"),S("replay_runtime_artifact_hash"),S("replay_dependency_manifest_hash"),S("replay_platform_contract_hash"),S("replay_canonical_serialization_contract_hash"),I("replay_result_schema_version"),T("replay_evaluation_instant"),S("replay_deterministic_seed_binding_hash"),I("attempt_number"),S("state"),T("started_at"),T("finished_at",True),S("replay_result_payload_hash",True),S("replay_calculation_trace_hash",True),S("replay_decision_trace_hash",True),S("replay_canonical_result_hash",True),J("structured_result",True),J("structured_error",True),J("provenance"),S("record_hash"),sa.PrimaryKeyConstraint("replay_execution_record_id"),sa.UniqueConstraint("replay_execution_record_id","record_hash"),sa.UniqueConstraint("original_calculation_result_record_id","attempt_number"),sa.ForeignKeyConstraint(["calculation_bundle_id","calculation_bundle_hash"],["calculation_bundles.calculation_bundle_id","calculation_bundles.calculation_bundle_hash"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["original_calculation_execution_record_id","original_calculation_execution_record_hash"],["calculation_execution_records.calculation_execution_record_id","calculation_execution_records.record_hash"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["original_calculation_result_record_id","original_calculation_result_record_hash"],["calculation_result_records.calculation_result_record_id","calculation_result_records.record_hash"],ondelete="RESTRICT"),sa.CheckConstraint("attempt_number > 0"),sa.CheckConstraint("state IN ('pending','validating','running','completed','rejected_incomplete','rejected_divergent','rejected_incompatible','failed','cancelled')"))
    op.create_table("replay_verification_records",S("replay_verification_record_id"),S("replay_execution_record_id"),S("replay_execution_record_hash"),S("calculation_bundle_id"),S("calculation_bundle_hash"),S("original_calculation_result_record_id"),S("original_calculation_result_record_hash"),S("original_canonical_result_hash"),S("replay_canonical_result_hash",True),B("result_payload_match"),B("calculation_trace_match"),B("decision_trace_match"),S("verification_outcome"),J("mismatch_manifest"),T("verified_at"),S("verifier"),J("provenance"),S("record_hash"),sa.PrimaryKeyConstraint("replay_verification_record_id"),sa.UniqueConstraint("replay_execution_record_id"),sa.UniqueConstraint("record_hash"),sa.ForeignKeyConstraint(["replay_execution_record_id","replay_execution_record_hash"],["replay_execution_records.replay_execution_record_id","replay_execution_records.record_hash"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["calculation_bundle_id","calculation_bundle_hash"],["calculation_bundles.calculation_bundle_id","calculation_bundles.calculation_bundle_hash"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["original_calculation_result_record_id","original_calculation_result_record_hash"],["calculation_result_records.calculation_result_record_id","calculation_result_records.record_hash"],ondelete="RESTRICT"),sa.CheckConstraint("verification_outcome IN ('match','mismatch','inconclusive')"))
    op.execute("""CREATE FUNCTION adr020_validate_calculation_replay_chain() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
      IF TG_TABLE_NAME='calculation_bundles' AND NOT EXISTS (SELECT 1 FROM generation_fence_records f JOIN activation_generations g ON g.activation_generation_id=NEW.activation_generation_id AND g.record_hash=NEW.activation_generation_record_hash JOIN consumer_application_records a ON a.consumer_application_record_id=NEW.consumer_application_record_id AND a.record_hash=NEW.consumer_application_record_hash JOIN replica_checkpoint_records r ON r.replica_checkpoint_record_id=NEW.replica_checkpoint_record_id AND r.record_hash=NEW.replica_checkpoint_record_hash WHERE f.generation_fence_record_id=NEW.generation_fence_record_id AND f.record_hash=NEW.generation_fence_record_hash AND g.is_complete AND a.application_result='applied' AND COALESCE((a.structured_result->>'application_complete')::boolean,false) AND r.consumer_application_record_id=a.consumer_application_record_id AND (f.scope_hash,f.generation_sequence,f.fencing_token,f.activation_generation_id,f.composition_hash)=(NEW.scope_hash,NEW.generation_sequence,NEW.fencing_token,NEW.activation_generation_id,NEW.composition_hash)) THEN RAISE EXCEPTION 'ADR-020 exact integral generation, fence, contract, application and checkpoint required';
      ELSIF TG_TABLE_NAME='calculation_result_records' AND NOT EXISTS (SELECT 1 FROM calculation_execution_records e WHERE e.calculation_execution_record_id=NEW.calculation_execution_record_id AND e.record_hash=NEW.calculation_execution_record_hash AND e.calculation_bundle_id=NEW.calculation_bundle_id AND e.calculation_bundle_hash=NEW.calculation_bundle_hash AND e.state='completed' AND COALESCE((e.structured_result->>'calculation_complete')::boolean,false)) THEN RAISE EXCEPTION 'ADR-020 partial result or result before completed execution forbidden';
      ELSIF TG_TABLE_NAME='replay_verification_records' AND NEW.verification_outcome='match' AND (NEW.replay_canonical_result_hash IS DISTINCT FROM NEW.original_canonical_result_hash OR NOT NEW.result_payload_match OR NOT NEW.calculation_trace_match OR NOT NEW.decision_trace_match OR NEW.mismatch_manifest NOT IN ('[]'::jsonb,'{}'::jsonb)) THEN RAISE EXCEPTION 'ADR-020 partial verification cannot be match'; END IF; RETURN NEW; END $$;""")
    for table in TABLES:
        op.execute(f"CREATE TRIGGER trg_{table}_validate_insert BEFORE INSERT ON {table} FOR EACH ROW EXECUTE FUNCTION adr020_validate_calculation_replay_chain()")
        _append_only(table)


def downgrade():
    raise RuntimeError("Migration 0027_adr020_calc_replay is irreversible by ratified ADR-020 append-only requirements")
