"""add uf_cobertura to inteligencia_snapshots

Revision ID: 617775975286
Revises: 0d4ae9c423e0
Create Date: 2026-03-24 09:48:48.579772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617775975286'
down_revision: Union[str, Sequence[str], None] = '0d4ae9c423e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inteligencia_snapshots', sa.Column('uf_cobertura', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inteligencia_snapshots', 'uf_cobertura')
    # ### end Alembic commands ###
